export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function EventLayout({ children }: { children: React.ReactNode }) {
	return (
		<>
			<h1>Header</h1>

			{children}
			<footer>
				<h1>Footer</h1>
			</footer>
		</>
	);
}
